"""Interface to events form an Xbox controller

Evan Goris
2015
"""

import os

from evdev import InputDevice, list_devices


def printevent(event):
    import evdev.ecodes
    print event.code, event.type, event.value
    print evdev.ecodes.bytype[event.type][event.code]
        
class XCEvents(object):
    """Manages a sequence of events from an Xbox controller

    Objects of this class poll for events from /dev/input
    An Xbox controller can be made a device under /dev/input with
    the userspace driver `xboxdrv`.    
    
    Responsibilities:
        Delivering Xbox events, non-blocking to interested parties.
        
    Implementation:
        Resource management: Thread that polls the controller
        
    """
    def __init__(self, callbacks=None):

        # The xbox device
        #
        self._xbox      = self._finddevice()

        # List of callbacks that will be called
        # when xbox events occur
        #
        self._callbacks = callbacks or []

        # The thread that polls the controller
        # Will be initialized in __enter__()
        #
        self._t         = None

    def add_callback(self, callback):
        self._callbacks.append(callback)
        
    def absinfo(self, type_):
        """Get information on an absolute input axis
        
        Args:
            type_ (int or str): Code or symbolic name of an absolute axis
            
        Returns:
            AbsInfo: Named tuple with info on `type_`
        """
        import evdev.ecodes
        cap = self._xbox.capabilities(absinfo=True, verbose=False)
        if type(type_)==str:
            typecode = evdev.ecodes.ecodes[type_]
        else:
            typecode = type_
        abscode = evdev.ecodes.ecodes['EV_ABS']
        for info in cap[abscode]:
            if info[0]==typecode:
                return info[1]
            
    
    def _finddevice(self):
        """Search for the device that represents the xbox controller
        
        Returns:
            InputDevice: The xbox controller
            
        Raises:
            IOError: When no controller can be found
        """
        devices = [ InputDevice(fn) for fn in list_devices()]
        for dev in devices:
            if dev.name.startswith('Xbox Gamepad'):
                return dev
        
        raise IOError("No Xbox controller found")
    
    def __enter__(self):
        """Fire up a thread that polls the controller
        """
        # Initialize signalling file descriptors to break
        # the endless select loop. If anything is written
        # over this pipe then the event sequence generated
        # by self.eventsequence() will end.
        #
        self.__signalrfd, self.__signalwfd = os.pipe()

        # Start up a thread that waits for events from
        # the controller.
        #
        import threading
        self._t = threading.Thread(target=self._processevents,args=())
        self._t.deamon = True
        self._t.start()

        return self
        
    def __exit__(self, type_, value, traceback):
        """Release resources
        """
        
        # Signal the event sequence to end and thus the
        # thread to end.
        #
        os.write(self.__signalwfd, "STOP")

        # Wait for tread to finish
        #
        self._t.join()
        self._t = None

        # Close communication channels
        #
        os.close(self.__signalrfd)
        os.close(self.__signalwfd)    
        
    def _processevents(self):
        """Process events from the sequence generated by the controller
        
            The sequence of events is generated by self._eventsequence()
        """
        for event in self._eventsequence():
            for callback in self._callbacks:
                callback(event)
        
    def _eventsequence(self):
        """Generate a sequence of xbox events
        
            This sequence ends when something is red from self._signalrfd
            
        Yields:
            Event: event generated by xbox controller
            
        """
        from select import select
        while True:
            r, w, x = select([self._xbox.fd,self.__signalrfd], [],[])
            if self.__signalrfd in r:
                break
            else:
                for event in self._xbox.read():
                    yield event